require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
  pod 'CapacitorNativeBiometric', :path => '../../node_modules/capacitor-native-biometric'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  
  # Use update_code_signing_settings with targets instead of bundle_id
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # Remove any conflicting bundle identifier settings
        config.build_settings.delete('PRODUCT_BUNDLE_IDENTIFIER')
        
        # Set unique bundle identifiers for each target
        case target.name
        when 'Capacitor'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.capacitor'
        when 'CapacitorCordova'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.cordova'
        when 'RevenuecatPurchasesCapacitor'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.revenuecat'
        when 'CapacitorNativeBiometric'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.biometric'
        when 'RevenueCat'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.revenuecatsdk'
        when 'PurchasesHybridCommon'
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.hybridcommon'
        when /Pods-/
          config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.framework.pods'
        end
        
        # Ensure proper code signing settings
        config.build_settings['CODE_SIGN_IDENTITY'] = ''
        config.build_settings['CODE_SIGN_STYLE'] = 'Automatic'
      end
    end
  end
end
