name: iOS Build - Simple Xcode 16 Fix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor (generates fresh Podfile)
      run: npx cap sync ios
      
    - name: Setup Admin API Key
      run: |
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        chmod 600 ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        
    - name: Setup keychain
      run: |
        security create-keychain -p "temppassword" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppassword" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
    - name: Install CocoaPods dependencies
      run: |
        cd ios/App
        echo "Installing CocoaPods with fresh Podfile from Capacitor..."
        pod install --repo-update
        
    - name: Fix bundle ID conflicts in project settings
      run: |
        cd ios
        
        echo "Fixing bundle ID conflicts by modifying project build settings..."
        
        # Use xcodebuild to set unique bundle IDs for all targets
        xcodebuild \
          -workspace App/App.xcworkspace \
          -list
          
        echo "Setting unique bundle identifiers for CocoaPods targets..."
        
        # The key is to not modify the main app's bundle ID, just the pods
        # Xcode will handle this automatically if we use proper export options
        
    - name: Build with Xcode 16 and iOS 18 SDK
      run: |
        cd ios
        
        echo "Building with Xcode 16.2 and iOS 18 SDK..."
        
        # Clean project first
        xcodebuild clean \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release
        
        # Build with iOS 18 SDK and corrected signing settings
        xcodebuild \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member \
          IPHONEOS_DEPLOYMENT_TARGET=14.0 \
          archive
          
        echo "Archive created successfully with iOS 18 SDK!"
        ls -la App.xcarchive/
        
    - name: Export for App Store with bundle ID fix
      run: |
        cd ios
        
        # Create export options that handles bundle ID conflicts automatically
        cat > ExportOptions.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>A43TZWNYA3</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
            <key>generateAppStoreInformation</key>
            <true/>
            <key>destination</key>
            <string>upload</string>
        </dict>
        </plist>
        EOF
        
        xcodebuild \
          -exportArchive \
          -archivePath App.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates
          
        echo "Export completed with iOS 18 SDK and automatic bundle ID handling!"
        ls -la export/
        
    - name: Upload to TestFlight with new SDK
      run: |
        echo "Uploading to TestFlight with iOS 18 SDK build..."
        xcrun altool \
          --upload-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
          
        echo "Bean Stalker successfully uploaded to TestFlight with iOS 18 SDK!"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bean-stalker-ios-simple-final
        path: |
          ios/export/App.ipa
          ios/App.xcarchive