name: iOS Debug - Check What We Have
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Apple Certificate
      run: |
        echo "${{ secrets.CERTIFICATES_P12 }}" | base64 -d > certificate.p12
        security create-keychain -p "" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "${{ secrets.CERTIFICATES_PASSWORD }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain
        
    - name: Install Provisioning Profile
      run: |
        echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 -d > profile.mobileprovision
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        UUID=$(grep -aA1 UUID profile.mobileprovision | grep string | sed 's/<[^>]*>//g' | xargs)
        cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
        
    - name: Debug - Show what we have
      run: |
        echo "=== SIGNING IDENTITIES ==="
        security find-identity -v -p codesigning
        
        echo -e "\n=== PROVISIONING PROFILES ==="
        ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
        
        echo -e "\n=== PROFILE DETAILS ==="
        security cms -D -i profile.mobileprovision | plutil -p -
        
        echo -e "\n=== BUNDLE ID CHECK ==="
        security cms -D -i profile.mobileprovision | grep -A3 "application-identifier"
        
        echo -e "\n=== TEAM ID CHECK ==="
        security cms -D -i profile.mobileprovision | grep -A1 "com.apple.developer.team-identifier"
        
        echo -e "\n=== PROFILE TYPE ==="
        security cms -D -i profile.mobileprovision | grep -A1 "get-task-allow"