name: iOS Build - Using TestFlight Admin Key
on:
  workflow_dispatch:

env:
  # Use the TestFlight key (8G8SZCTK49) which has Admin access instead of GitHub Actions key
  TESTFLIGHT_API_KEY_ID: "8G8SZCTK49"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync ios
      
    - name: Setup TestFlight Admin API Key
      run: |
        mkdir -p ~/private_keys
        # Use the APPSTORE_API_PRIVATE_KEY secret but with TestFlight key ID
        echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${TESTFLIGHT_API_KEY_ID}.p8
        chmod 600 ~/private_keys/AuthKey_${TESTFLIGHT_API_KEY_ID}.p8
        
        echo "Using TestFlight Admin key: ${TESTFLIGHT_API_KEY_ID}"
        
    - name: Setup keychain
      run: |
        security create-keychain -p "temppassword" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppassword" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
    - name: Build with Admin API key access
      run: |
        cd ios
        
        echo "Building with TestFlight Admin API key for certificate access..."
        
        xcodebuild \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${TESTFLIGHT_API_KEY_ID}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${TESTFLIGHT_API_KEY_ID}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member \
          archive
          
        echo "Archive completed with Admin key!"
        ls -la App.xcarchive/
        
    - name: Show downloaded certificates
      run: |
        echo "Certificates downloaded with Admin access:"
        security find-identity -v -p codesigning
        
    - name: Export for App Store
      run: |
        cd ios
        
        cat > ExportOptions.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>A43TZWNYA3</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        echo "Exporting with Admin certificate access..."
        xcodebuild \
          -exportArchive \
          -archivePath App.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${TESTFLIGHT_API_KEY_ID}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${TESTFLIGHT_API_KEY_ID}.p8 \
          -allowProvisioningUpdates
          
        echo "Export completed!"
        ls -la export/
        
    - name: Upload to TestFlight with Admin key
      run: |
        echo "Uploading to TestFlight with Admin access..."
        xcrun altool \
          --upload-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${TESTFLIGHT_API_KEY_ID}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
          
        echo "Successfully uploaded Bean Stalker to TestFlight with Admin key!"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bean-stalker-testflight-admin
        path: |
          ios/export/App.ipa
          ios/App.xcarchive