name: iOS Build - Bundle ID Fixed
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Latest Xcode (iOS 18 SDK)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync ios
      
    - name: Reinstall pods with bundle ID fixes
      run: |
        cd ios/App
        echo "Reinstalling CocoaPods with bundle ID collision fixes..."
        
        # Clean existing pods
        rm -rf Pods
        rm -f Podfile.lock
        
        # Install with the updated Podfile that has bundle ID fixes
        pod install --repo-update
        
        echo "CocoaPods installed with unique bundle identifiers!"
        
    - name: Setup Admin API Key
      run: |
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        chmod 600 ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        
    - name: Setup keychain
      run: |
        security create-keychain -p "temppassword" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppassword" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
    - name: Build with iOS 18 SDK and fixed bundle IDs
      run: |
        cd ios
        
        echo "Building with Xcode 16.2, iOS 18 SDK, and fixed bundle identifiers..."
        echo "Current Xcode version:"
        xcodebuild -version
        
        # Clean project first
        xcodebuild clean \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release
        
        # Build with fixed bundle IDs and iOS 18 SDK
        xcodebuild \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member \
          IPHONEOS_DEPLOYMENT_TARGET=14.0 \
          archive
          
        echo "Archive created successfully with iOS 18 SDK and fixed bundle IDs!"
        ls -la App.xcarchive/
        
    - name: Export for App Store with collision resolution
      run: |
        cd ios
        
        cat > ExportOptions.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>A43TZWNYA3</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
            <key>generateAppStoreInformation</key>
            <true/>
            <key>stripSwiftSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        xcodebuild \
          -exportArchive \
          -archivePath App.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates
          
        echo "Export completed with iOS 18 SDK and fixed bundle IDs!"
        ls -la export/
        
    - name: Validate app with bundle ID fixes
      run: |
        echo "Validating Bean Stalker app with bundle ID collision fixes..."
        xcrun altool \
          --validate-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
        
    - name: Upload to TestFlight
      run: |
        echo "Uploading Bean Stalker to TestFlight with iOS 18 SDK and fixed bundle IDs..."
        xcrun altool \
          --upload-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
          
        echo "Bean Stalker successfully uploaded to TestFlight!"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bean-stalker-ios-bundle-fixed
        path: |
          ios/export/App.ipa
          ios/App.xcarchive