name: Simple iOS Build Test

on:
  workflow_dispatch:

jobs:
  test-build:
    runs-on: macos-13
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List project structure
      run: |
        echo "Project root contents:"
        ls -la
        echo "Checking for ios folder:"
        ls -la ios/ || echo "iOS folder not found"
        echo "Checking for Capacitor config:"
        cat capacitor.config.ts || echo "Capacitor config not found"
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm ci
        echo "Dependencies installed successfully"
        
    - name: Build web app
      run: |
        npx vite build
        echo "Web build completed"
        ls -la dist/public/ || echo "dist/public folder not found"
        ls -la dist/public/index.html || echo "index.html not found"
        
    - name: Setup Capacitor
      run: |
        npx cap sync ios
        echo "Capacitor sync completed"
        echo "iOS project structure:"
        ls -la ios/App/ || echo "iOS App folder not found"
        
    - name: Check Xcode setup
      run: |
        xcodebuild -version
        echo "Available schemes:"
        cd ios/App && xcodebuild -list
        
    - name: Verify secrets availability
      run: |
        echo "Checking secrets..."
        echo "IOS_DISTRIBUTION_CERT length: ${#IOS_DISTRIBUTION_CERT}"
        echo "TEAM_ID: $TEAM_ID"
        echo "APPSTORE_USERNAME: $APPSTORE_USERNAME"
      env:
        IOS_DISTRIBUTION_CERT: ${{ secrets.IOS_DISTRIBUTION_CERT }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        APPSTORE_USERNAME: ${{ secrets.APPSTORE_USERNAME }}