name: iOS Build - Simple Fix
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode 16.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Build
      env:
        VITE_REVENUECAT_API_KEY: ${{ secrets.VITE_REVENUECAT_API_KEY }}
        OMNISEND_API_KEY: ${{ secrets.OMNISEND_API_KEY }}
        VITE_FORCE_SANDBOX: true
        # Twilio SMS Integration Secrets
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        TWILIO_SENDER_ID: ${{ secrets.TWILIO_SENDER_ID }}
        # Apple Wallet Integration Secrets
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APPLE_WALLET_CERT_PASSWORD: ${{ secrets.APPLE_WALLET_CERT_PASSWORD }}
        APPLE_WALLET_CERT_BASE64: ${{ secrets.APPLE_WALLET_CERT_BASE64 }}
        APPLE_WALLET_WWDR_BASE64: ${{ secrets.APPLE_WALLET_WWDR_BASE64 }}
        # Square API Integration Secrets (Sandbox)
        SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
        SQUARE_APPLICATION_ID: ${{ secrets.SQUARE_APPLICATION_ID }}
        SQUARE_LOCATION_ID: ${{ secrets.SQUARE_LOCATION_ID }}
        SQUARE_WEBHOOK_SIGNATURE_KEY: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}
        # Square API Integration Secrets (Production)
        SQUARE_ACCESS_TOKEN_PROD: ${{ secrets.SQUARE_ACCESS_TOKEN_PROD }}
        SQUARE_APPLICATION_ID_PROD: ${{ secrets.SQUARE_APPLICATION_ID_PROD }}
        SQUARE_APPLICATION_SECRET_PROD: ${{ secrets.SQUARE_APPLICATION_SECRET_PROD }}
        SQUARE_LOCATION_ID_PROD: ${{ secrets.SQUARE_LOCATION_ID_PROD }}
        SQUARE_WEBHOOK_SIGNATURE_KEY_PROD: ${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY_PROD }}
      run: |
        # Export environment variables for all subsequent steps
        echo "VITE_REVENUECAT_API_KEY=${{ secrets.VITE_REVENUECAT_API_KEY }}" >> $GITHUB_ENV
        echo "OMNISEND_API_KEY=${{ secrets.OMNISEND_API_KEY }}" >> $GITHUB_ENV
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> $GITHUB_ENV
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> $GITHUB_ENV
        echo "TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}" >> $GITHUB_ENV
        echo "TWILIO_SENDER_ID=${{ secrets.TWILIO_SENDER_ID }}" >> $GITHUB_ENV
        echo "APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}" >> $GITHUB_ENV
        echo "APPLE_WALLET_CERT_PASSWORD=${{ secrets.APPLE_WALLET_CERT_PASSWORD }}" >> $GITHUB_ENV
        echo "APPLE_WALLET_CERT_BASE64=${{ secrets.APPLE_WALLET_CERT_BASE64 }}" >> $GITHUB_ENV
        echo "APPLE_WALLET_WWDR_BASE64=${{ secrets.APPLE_WALLET_WWDR_BASE64 }}" >> $GITHUB_ENV
        echo "SQUARE_ACCESS_TOKEN=${{ secrets.SQUARE_ACCESS_TOKEN }}" >> $GITHUB_ENV
        echo "SQUARE_APPLICATION_ID=${{ secrets.SQUARE_APPLICATION_ID }}" >> $GITHUB_ENV
        echo "SQUARE_LOCATION_ID=${{ secrets.SQUARE_LOCATION_ID }}" >> $GITHUB_ENV
        echo "SQUARE_WEBHOOK_SIGNATURE_KEY=${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}" >> $GITHUB_ENV
        echo "SQUARE_ACCESS_TOKEN_PROD=${{ secrets.SQUARE_ACCESS_TOKEN_PROD }}" >> $GITHUB_ENV
        echo "SQUARE_APPLICATION_ID_PROD=${{ secrets.SQUARE_APPLICATION_ID_PROD }}" >> $GITHUB_ENV
        echo "SQUARE_APPLICATION_SECRET_PROD=${{ secrets.SQUARE_APPLICATION_SECRET_PROD }}" >> $GITHUB_ENV
        echo "SQUARE_LOCATION_ID_PROD=${{ secrets.SQUARE_LOCATION_ID_PROD }}" >> $GITHUB_ENV
        echo "SQUARE_WEBHOOK_SIGNATURE_KEY_PROD=${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY_PROD }}" >> $GITHUB_ENV
        
        # Verify the secrets are accessible
        echo "=== RevenueCat API Key Verification ==="
        if [ -z "${{ secrets.VITE_REVENUECAT_API_KEY }}" ]; then
          echo "❌ GitHub secret VITE_REVENUECAT_API_KEY is empty or not set"
          echo "Please configure the secret in GitHub repository settings"
          exit 1
        else
          echo "✅ GitHub secret VITE_REVENUECAT_API_KEY is configured"
          echo "Key length: ${#VITE_REVENUECAT_API_KEY} characters"
          echo "Key starts with: ${VITE_REVENUECAT_API_KEY:0:8}..."
        fi
        
        echo "=== Omnisend API Key Verification ==="
        if [ -z "${{ secrets.OMNISEND_API_KEY }}" ]; then
          echo "❌ GitHub secret OMNISEND_API_KEY is empty or not set"
          echo "Please configure the secret in GitHub repository settings"
          exit 1
        else
          echo "✅ GitHub secret OMNISEND_API_KEY is configured"
          echo "Key length: ${#OMNISEND_API_KEY} characters"
          echo "Key starts with: ${OMNISEND_API_KEY:0:8}..."
        fi
        
        echo "=== Twilio SMS Integration Verification ==="
        if [ -z "${{ secrets.TWILIO_ACCOUNT_SID }}" ]; then
          echo "❌ GitHub secret TWILIO_ACCOUNT_SID is empty or not set"
          echo "SMS functionality will be disabled"
        else
          echo "✅ GitHub secret TWILIO_ACCOUNT_SID is configured"
          echo "Account SID: ${TWILIO_ACCOUNT_SID:0:8}..."
        fi
        
        if [ -z "${{ secrets.TWILIO_AUTH_TOKEN }}" ]; then
          echo "❌ GitHub secret TWILIO_AUTH_TOKEN is empty or not set"
          echo "SMS functionality will be disabled"
        else
          echo "✅ GitHub secret TWILIO_AUTH_TOKEN is configured"
          echo "Token length: ${#TWILIO_AUTH_TOKEN} characters"
        fi
        
        if [ -z "${{ secrets.TWILIO_PHONE_NUMBER }}" ]; then
          echo "❌ GitHub secret TWILIO_PHONE_NUMBER is empty or not set"
          echo "SMS functionality will be disabled"
        else
          echo "✅ GitHub secret TWILIO_PHONE_NUMBER is configured: ${{ secrets.TWILIO_PHONE_NUMBER }}"
        fi
        
        echo "=== Apple Wallet Integration Verification ==="
        if [ -z "${{ secrets.APPLE_TEAM_ID }}" ]; then
          echo "❌ GitHub secret APPLE_TEAM_ID is empty or not set"
          echo "Apple Wallet integration will be disabled"
        else
          echo "✅ GitHub secret APPLE_TEAM_ID is configured: ${{ secrets.APPLE_TEAM_ID }}"
        fi
        
        if [ -z "${{ secrets.APPLE_WALLET_CERT_PASSWORD }}" ]; then
          echo "❌ GitHub secret APPLE_WALLET_CERT_PASSWORD is empty or not set"
          echo "Apple Wallet certificate signing will be disabled"
        else
          echo "✅ GitHub secret APPLE_WALLET_CERT_PASSWORD is configured"
        fi
        
        if [ -z "${{ secrets.APPLE_WALLET_CERT_BASE64 }}" ]; then
          echo "❌ GitHub secret APPLE_WALLET_CERT_BASE64 is empty or not set"
          echo "Apple Wallet certificate data missing"
        else
          echo "✅ GitHub secret APPLE_WALLET_CERT_BASE64 is configured"
          echo "Certificate data length: ${#APPLE_WALLET_CERT_BASE64} characters"
        fi
        
        echo "=== Square Production API Integration Verification ==="
        if [ -z "${{ secrets.SQUARE_ACCESS_TOKEN_PROD }}" ]; then
          echo "⚠️ GitHub secret SQUARE_ACCESS_TOKEN_PROD is empty or not set"
          echo "Will use sandbox Square API instead"
        else
          echo "✅ GitHub secret SQUARE_ACCESS_TOKEN_PROD is configured"
          echo "Production Kitchen Display integration enabled"
        fi
        
        if [ -z "${{ secrets.SQUARE_APPLICATION_ID_PROD }}" ]; then
          echo "⚠️ GitHub secret SQUARE_APPLICATION_ID_PROD is empty or not set"
        else
          echo "✅ GitHub secret SQUARE_APPLICATION_ID_PROD is configured"
          echo "App ID: ${SQUARE_APPLICATION_ID_PROD:0:12}..."
        fi
        
        if [ -z "${{ secrets.SQUARE_LOCATION_ID_PROD }}" ]; then
          echo "⚠️ GitHub secret SQUARE_LOCATION_ID_PROD is empty or not set"
        else
          echo "✅ GitHub secret SQUARE_LOCATION_ID_PROD is configured: ${{ secrets.SQUARE_LOCATION_ID_PROD }}"
        fi
        
        if [ -z "${{ secrets.SQUARE_APPLICATION_SECRET_PROD }}" ]; then
          echo "⚠️ GitHub secret SQUARE_APPLICATION_SECRET_PROD is empty or not set"
          echo "OAuth flows will be disabled in production"
        else
          echo "✅ GitHub secret SQUARE_APPLICATION_SECRET_PROD is configured"
          echo "OAuth authentication enabled"
        fi
        
        if [ -z "${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY_PROD }}" ]; then
          echo "⚠️ GitHub secret SQUARE_WEBHOOK_SIGNATURE_KEY_PROD is empty or not set"
          echo "Webhook verification will be disabled in production"
        else
          echo "✅ GitHub secret SQUARE_WEBHOOK_SIGNATURE_KEY_PROD is configured"
          echo "Webhook signature verification enabled"
        fi
        
        if [ -z "${{ secrets.APPLE_WALLET_WWDR_BASE64 }}" ]; then
          echo "❌ GitHub secret APPLE_WALLET_WWDR_BASE64 is empty or not set"
          echo "Apple Wallet WWDR certificate data missing"
        else
          echo "✅ GitHub secret APPLE_WALLET_WWDR_BASE64 is configured"
          echo "WWDR data length: ${#APPLE_WALLET_WWDR_BASE64} characters"
        fi
        
        echo "=== Square API Integration Verification ==="
        if [ -z "${{ secrets.SQUARE_ACCESS_TOKEN }}" ]; then
          echo "❌ GitHub secret SQUARE_ACCESS_TOKEN is empty or not set"
          echo "Square payment processing and Kitchen Display will be disabled"
        else
          echo "✅ GitHub secret SQUARE_ACCESS_TOKEN is configured"
          echo "Token length: ${#SQUARE_ACCESS_TOKEN} characters"
          echo "Token starts with: ${SQUARE_ACCESS_TOKEN:0:8}..."
        fi
        
        if [ -z "${{ secrets.SQUARE_APPLICATION_ID }}" ]; then
          echo "❌ GitHub secret SQUARE_APPLICATION_ID is empty or not set"
          echo "Square OAuth integration will be disabled"
        else
          echo "✅ GitHub secret SQUARE_APPLICATION_ID is configured: ${{ secrets.SQUARE_APPLICATION_ID }}"
        fi
        
        if [ -z "${{ secrets.SQUARE_LOCATION_ID }}" ]; then
          echo "❌ GitHub secret SQUARE_LOCATION_ID is empty or not set"
          echo "Square location-specific features will be disabled"
        else
          echo "✅ GitHub secret SQUARE_LOCATION_ID is configured: ${{ secrets.SQUARE_LOCATION_ID }}"
        fi
        
        if [ -z "${{ secrets.SQUARE_WEBHOOK_SIGNATURE_KEY }}" ]; then
          echo "❌ GitHub secret SQUARE_WEBHOOK_SIGNATURE_KEY is empty or not set"
          echo "Square webhook verification will be disabled"
        else
          echo "✅ GitHub secret SQUARE_WEBHOOK_SIGNATURE_KEY is configured"
          echo "Key length: ${#SQUARE_WEBHOOK_SIGNATURE_KEY} characters"
        fi
        
        # Create certificate files from base64 for the build
        echo "=== Creating Apple Wallet Certificate Files ==="
        mkdir -p certs
        if [ -n "$APPLE_WALLET_CERT_BASE64" ]; then
          echo "$APPLE_WALLET_CERT_BASE64" | base64 -d > certs/bean_stalker_pass_cert.p12
          echo "✅ Created Apple Wallet certificate file from GitHub secret"
        else
          echo "❌ APPLE_WALLET_CERT_BASE64 not available"
        fi
        
        if [ -n "$APPLE_WALLET_WWDR_BASE64" ]; then
          echo "$APPLE_WALLET_WWDR_BASE64" | base64 -d > certs/wwdr.pem
          echo "✅ Created WWDR certificate file from GitHub secret"
        else
          echo "❌ APPLE_WALLET_WWDR_BASE64 not available"
        fi
        
        # Verify certificate files were created
        ls -la certs/
        
        npm ci
        echo "Building with RevenueCat API Key: $(test -n "$VITE_REVENUECAT_API_KEY" && echo "CONFIGURED" || echo "MISSING")"
        echo "Building with Twilio SMS: $(test -n "$TWILIO_ACCOUNT_SID" && echo "CONFIGURED" || echo "MISSING")"
        echo "Building with Apple Wallet Certificates: $(test -f "certs/bean_stalker_pass_cert.p12" && echo "CONFIGURED" || echo "MISSING")"
        echo "Building with Square API: $(test -n "$SQUARE_ACCESS_TOKEN" && echo "CONFIGURED" || echo "MISSING")"
        echo "Building in development mode for sandbox IAP testing"
        
        # Embed certificates directly in server code for TestFlight builds
        echo "=== Embedding Apple Wallet certificates in server code ==="
        node embed-certificates.js
        
        # Build the app with embedded certificates
        VITE_FORCE_SANDBOX=true npm run build
        
        # Handle build output location issue
        echo "=== Verifying and fixing build output ==="
        ls -la dist/
        
        # Check if files are in dist/public and move them
        if [ -d "dist/public" ] && [ -f "dist/public/index.html" ]; then
          echo "Moving files from dist/public to dist/"
          cp -r dist/public/* dist/
          ls -la dist/
        fi
        
        if [ ! -f "dist/index.html" ]; then
          echo "Error: dist/index.html still not found after build"
          ls -la dist/
          exit 1
        fi
        echo "Build verification successful"
        
        # Verify environment variables are available for Capacitor
        echo "RevenueCat API Key for Capacitor sync: $(test -n "$VITE_REVENUECAT_API_KEY" && echo "CONFIGURED" || echo "MISSING")"
        echo "Apple Wallet Team ID: $(test -n "$APPLE_TEAM_ID" && echo "CONFIGURED" || echo "MISSING")"
        echo "Apple Wallet Cert Base64: $(test -n "$APPLE_WALLET_CERT_BASE64" && echo "CONFIGURED" || echo "MISSING")"
        echo "Apple Wallet WWDR Base64: $(test -n "$APPLE_WALLET_WWDR_BASE64" && echo "CONFIGURED" || echo "MISSING")"
        
        npx cap sync ios
        cd ios/App && pod install
        
    - name: Setup API Key
      run: |
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        chmod 600 ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        
    - name: Setup keychain
      run: |
        security create-keychain -p "temppassword" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppassword" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
    - name: Build archive
      env:
        VITE_REVENUECAT_API_KEY: ${{ secrets.VITE_REVENUECAT_API_KEY }}
        OMNISEND_API_KEY: ${{ secrets.OMNISEND_API_KEY }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APPLE_WALLET_CERT_PASSWORD: ${{ secrets.APPLE_WALLET_CERT_PASSWORD }}
        APPLE_WALLET_CERT_BASE64: ${{ secrets.APPLE_WALLET_CERT_BASE64 }}
        APPLE_WALLET_WWDR_BASE64: ${{ secrets.APPLE_WALLET_WWDR_BASE64 }}
      run: |
        cd ios
        xcodebuild archive \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member
        
    - name: Clean rebuild with fixed Podfile configuration
      env:
        VITE_REVENUECAT_API_KEY: ${{ secrets.VITE_REVENUECAT_API_KEY }}
        OMNISEND_API_KEY: ${{ secrets.OMNISEND_API_KEY }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        APPLE_WALLET_CERT_PASSWORD: ${{ secrets.APPLE_WALLET_CERT_PASSWORD }}
        APPLE_WALLET_CERT_BASE64: ${{ secrets.APPLE_WALLET_CERT_BASE64 }}
        APPLE_WALLET_WWDR_BASE64: ${{ secrets.APPLE_WALLET_WWDR_BASE64 }}
      run: |
        echo "=== Cleaning and rebuilding with fixed bundle IDs ==="
        
        # Clean everything for fresh build
        cd ios/App
        rm -rf Pods Podfile.lock
        rm -rf ~/Library/Developer/Xcode/DerivedData
        
        # Install pods with updated Podfile
        pod install --repo-update
        
        # Verify Podfile configuration applied
        echo "=== Verifying Pod target bundle IDs ==="
        grep -r "PRODUCT_BUNDLE_IDENTIFIER" Pods/Target\ Support\ Files/ | head -10 || echo "No bundle ID conflicts found"
        
        # Fix build settings that cause archive conflicts
        echo "=== Fixing build configuration conflicts ==="
        
        # Override problematic build settings
        xcodebuild clean -workspace App.xcworkspace -scheme App
        
        xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -archivePath "../../ios/App-clean.xcarchive" \
          -configuration Debug \
          -destination generic/platform=iOS \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          SWIFT_OPTIMIZATION_LEVEL=-O \
          SWIFT_COMPILATION_MODE=wholemodule
        
    - name: Export for App Store  
      run: |
        cd ios
        cat > ExportOptions.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>A43TZWNYA3</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
            <key>stripSwiftSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        xcodebuild -exportArchive \
          -archivePath App-clean.xcarchive \
          -exportPath export-clean \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration
        
    - name: Upload to TestFlight
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file "ios/export-clean/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
        
    - name: Save build
      uses: actions/upload-artifact@v4
      with:
        name: bean-stalker-mobile-connectivity-fix
        path: ios/export-clean/App.ipa