name: iOS Build and TestFlight Upload

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npx vite build
      
    - name: Setup Capacitor
      run: npx cap sync ios
      
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
        
    - name: Build and Archive iOS app
      uses: yukiarrr/ios-build-action@v1.11.0
      with:
        project-path: ios/App/App.xcodeproj
        p12-base64: ${{ secrets.IOS_DISTRIBUTION_CERT }}
        p12-password: ${{ secrets.IOS_CERT_PASSWORD }}
        mobileprovision-base64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        code-signing-identity: iPhone Distribution
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: ios/App/App.xcworkspace
        scheme: App
        export-method: app-store
        configuration: Release
          
    - name: Upload to TestFlight
      run: |
        xcrun altool --upload-app \
          --type ios \
          --file output.ipa \
          --username "${{ secrets.APPSTORE_USERNAME }}" \
          --password "${{ secrets.APPSTORE_PASSWORD }}"