name: iOS TestFlight Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build and Deploy to TestFlight
    runs-on: macos-14
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        
    - name: Install Dependencies
      run: |
        npm ci --prefer-offline --no-audit --silent
        
    - name: Build Web Application
      run: |
        NODE_ENV=production npm run build
        
    - name: Setup iOS Environment
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
        gem install cocoapods --no-document --quiet
        
    - name: Sync Capacitor
      run: |
        npx cap sync ios --no-open
        
    - name: Install iOS Dependencies
      working-directory: ios/App
      run: |
        rm -rf Pods/ Podfile.lock .symlinks/
        pod install --silent || pod install --verbose
        
    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v3
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        
    - name: Import Provisioning Profile
      uses: apple-actions/download-provisioning-profiles@v3
      with:
        bundle-id: com.beanstalker.member
        profile-type: IOS_APP_STORE
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        
    - name: Build iOS Archive
      working-directory: ios/App
      run: |
        xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -destination "generic/platform=iOS" \
          -archivePath build.xcarchive \
          -configuration Release \
          CODE_SIGN_STYLE=Manual \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member
          
    - name: Export IPA
      working-directory: ios/App
      run: |
        xcodebuild -exportArchive \
          -archivePath build.xcarchive \
          -exportPath build \
          -exportOptionsPlist ../../.github/workflows/ExportOptions.plist
          
    - name: Upload to TestFlight
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ios/App/build/App.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ios-build-artifacts
        path: |
          ios/App/build/
          ios/App/*.xcarchive