name: iOS Build - Clean Solution
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Latest Xcode (iOS 18 SDK)
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.2'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build web app
      run: npm run build
      
    - name: Sync Capacitor
      run: npx cap sync ios
      
    - name: Fix bundle ID collisions cleanly
      run: |
        cd ios/App
        echo "Applying clean bundle ID collision fix..."
        
        # Clean existing pods
        rm -rf Pods
        rm -f Podfile.lock
        
        # Create clean Podfile with minimal bundle ID fixes
        cat > Podfile << 'EOF'
        require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

        platform :ios, '14.0'
        use_frameworks!

        install! 'cocoapods', :disable_input_output_paths => true

        def capacitor_pods
          pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
          pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
          pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
          pod 'CapacitorNativeBiometric', :path => '../../node_modules/capacitor-native-biometric'
        end

        target 'App' do
          capacitor_pods
        end

        post_install do |installer|
          assertDeploymentTarget(installer)
          
          # Apply minimal bundle ID fixes only where needed
          installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              # Only set bundle IDs for specific problematic targets
              case target.name
              when 'Capacitor'
                config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.member.capacitor'
              when 'CapacitorCordova'
                config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.member.cordova'
              when 'RevenuecatPurchasesCapacitor'
                config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.member.revenuecat'
              when 'CapacitorNativeBiometric'
                config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.beanstalker.member.biometric'
              end
              
              # Keep modules enabled for proper Swift compilation
              config.build_settings['DEFINES_MODULE'] = 'YES'
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            end
          end
        end
        EOF
        
        # Install pods with clean configuration
        pod install --repo-update
        
        echo "CocoaPods installed with clean bundle ID fixes!"
        
    - name: Setup Admin API Key
      run: |
        mkdir -p ~/private_keys
        echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        chmod 600 ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        
    - name: Setup keychain
      run: |
        security create-keychain -p "temppassword" build.keychain
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "temppassword" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
        
    - name: Build with clean configuration
      run: |
        cd ios
        
        echo "Building with clean bundle ID fixes and iOS 18 SDK..."
        echo "Current Xcode version:"
        xcodebuild -version
        
        # Clean build
        xcodebuild clean \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release
        
        # Build with clean settings
        xcodebuild \
          -workspace App/App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination generic/platform=iOS \
          -archivePath App.xcarchive \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates \
          -allowProvisioningDeviceRegistration \
          CODE_SIGN_STYLE=Automatic \
          CODE_SIGN_IDENTITY="" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          DEVELOPMENT_TEAM=A43TZWNYA3 \
          PRODUCT_BUNDLE_IDENTIFIER=com.beanstalker.member \
          IPHONEOS_DEPLOYMENT_TARGET=14.0 \
          SWIFT_VERSION=5.0 \
          archive
          
        echo "Archive created successfully!"
        ls -la App.xcarchive/
        
    - name: Export with clean configuration
      run: |
        cd ios
        
        cat > ExportOptions.plist << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>A43TZWNYA3</string>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>manageAppVersionAndBuildNumber</key>
            <true/>
            <key>generateAppStoreInformation</key>
            <true/>
            <key>stripSwiftSymbols</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        xcodebuild \
          -exportArchive \
          -archivePath App.xcarchive \
          -exportPath export \
          -exportOptionsPlist ExportOptions.plist \
          -authenticationKeyIssuerID "${{ secrets.APPSTORE_ISSUER_ID }}" \
          -authenticationKeyID "${{ secrets.APPSTORE_API_KEY_ID }}" \
          -authenticationKeyPath ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8 \
          -allowProvisioningUpdates
          
        echo "Export completed successfully!"
        ls -la export/
        
    - name: Validate before upload
      run: |
        echo "Validating Bean Stalker app..."
        xcrun altool \
          --validate-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
        
    - name: Upload to TestFlight
      run: |
        echo "Uploading Bean Stalker to TestFlight..."
        xcrun altool \
          --upload-app \
          --type ios \
          --file "ios/export/App.ipa" \
          --apiKey "${{ secrets.APPSTORE_API_KEY_ID }}" \
          --apiIssuer "${{ secrets.APPSTORE_ISSUER_ID }}" \
          --verbose
          
        echo "Bean Stalker successfully uploaded to TestFlight!"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bean-stalker-ios-clean-success
        path: |
          ios/export/App.ipa
          ios/App.xcarchive